version: '3.3'

services:
  web-app:
    
    image: ap88/python-flask:002

    build: .
    
    container_name: python-flask
    ports:
      - "5000:5000"
    volumes:
      - ./storage:/app/storage
    restart: always
